// <auto-generated />
using System;
using Clothsy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clothsy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120103734_Clothsy")]
    partial class Clothsy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clothsy.Models.Donation.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedHubId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClothingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DonationId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DonorUserId")
                        .HasColumnType("int");

                    b.Property<string>("Photo1Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Photo2Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Photo3Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedHubId");

                    b.HasIndex("DonationId")
                        .IsUnique();

                    b.HasIndex("DonorUserId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.Hub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Hubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = " Trivandrum, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3555),
                            District = "Trivandrum",
                            Email = "clothsy.trivandrum@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Trivandrum",
                            Phone = "+91 90000 00000"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kollam, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3559),
                            District = "Kollam",
                            Email = "clothsy.kollam@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kollam",
                            Phone = "+91 90000 00001"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Pathanamthitta, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3560),
                            District = "Pathanamthitta",
                            Email = "clothsy.pathanamthitta@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Pathanamthitta",
                            Phone = "+91 90000 00002"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Alappuzha, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3562),
                            District = "Alappuzha",
                            Email = "clothsy.alappuzha@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Alappuzha",
                            Phone = "+91 90000 00003"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Kottayam, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3563),
                            District = "Kottayam",
                            Email = "clothsy.kottayam@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kottayam",
                            Phone = "+91 90000 00004"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Idukki, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3565),
                            District = "Idukki",
                            Email = "clothsy.idukki@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Idukki",
                            Phone = "+91 90000 00005"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Ernakulam, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3566),
                            District = "Ernakulam",
                            Email = "clothsy.ernakulam@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Ernakulam",
                            Phone = "+91 90000 00006"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Thrissur, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3568),
                            District = "Thrissur",
                            Email = "clothsy.thrissur@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Thrissur",
                            Phone = "+91 90000 00007"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Palakkad, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3569),
                            District = "Palakkad",
                            Email = "clothsy.palakkad@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Palakkad",
                            Phone = "+91 90000 00008"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Malappuram, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3571),
                            District = "Malappuram",
                            Email = "clothsy.malappuram@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Malappuram",
                            Phone = "+91 90000 00009"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Kozhikode, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3572),
                            District = "Kozhikode",
                            Email = "clothsy.kozhikode@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kozhikode",
                            Phone = "+91 90000 00010"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Wayanad, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3574),
                            District = "Wayanad",
                            Email = "clothsy.wayanad@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Wayanad",
                            Phone = "+91 90000 00011"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Kannur, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3575),
                            District = "Kannur",
                            Email = "clothsy.kannur@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kannur",
                            Phone = "+91 90000 00012"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Kasaragod, Kerala",
                            CreatedAt = new DateTime(2025, 11, 20, 10, 37, 34, 364, DateTimeKind.Utc).AddTicks(3577),
                            District = "Kasaragod",
                            Email = "clothsy.kasaragod@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kasaragod",
                            Phone = "+91 90000 00013"
                        });
                });

            modelBuilder.Entity("Clothsy.Models.SignupModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.Donation", b =>
                {
                    b.HasOne("Clothsy.Models.Donation.Hub", "AssignedHub")
                        .WithMany()
                        .HasForeignKey("AssignedHubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clothsy.Models.SignupModels.User", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedHub");

                    b.Navigation("Donor");
                });
#pragma warning restore 612, 618
        }
    }
}
