// <auto-generated />
using System;
using Clothsy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clothsy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260123043711_SupportTicketReplies")]
    partial class SupportTicketReplies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clothsy.Data.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AutoArchiveDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("SupportEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedHubId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClothingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DonationId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DonorUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ThumbnailImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedHubId");

                    b.HasIndex("DonorUserId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.DonationImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DonationId");

                    b.ToTable("DonationImages");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.DonationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<int?>("DonationId1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("DonationId");

                    b.HasIndex("DonationId1");

                    b.HasIndex("RequesterId");

                    b.ToTable("DonationRequests");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.Hub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HubCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WorkingDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Hubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = " Trivandrum, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7859),
                            District = "Trivandrum",
                            DistrictId = 0,
                            Email = "clothsy.trivandrum@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Trivandrum",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00000",
                            WorkingDays = ""
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kollam, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7864),
                            District = "Kollam",
                            DistrictId = 0,
                            Email = "clothsy.kollam@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kollam",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00001",
                            WorkingDays = ""
                        },
                        new
                        {
                            Id = 3,
                            Address = "Pathanamthitta, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7866),
                            District = "Pathanamthitta",
                            DistrictId = 0,
                            Email = "clothsy.pathanamthitta@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Pathanamthitta",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00002",
                            WorkingDays = ""
                        },
                        new
                        {
                            Id = 4,
                            Address = "Alappuzha, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7868),
                            District = "Alappuzha",
                            DistrictId = 0,
                            Email = "clothsy.alappuzha@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Alappuzha",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00003",
                            WorkingDays = ""
                        },
                        new
                        {
                            Id = 5,
                            Address = "Kottayam, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7869),
                            District = "Kottayam",
                            DistrictId = 0,
                            Email = "clothsy.kottayam@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kottayam",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00004",
                            WorkingDays = ""
                        },
                        new
                        {
                            Id = 6,
                            Address = "Idukki, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7871),
                            District = "Idukki",
                            DistrictId = 0,
                            Email = "clothsy.idukki@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Idukki",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00005",
                            WorkingDays = ""
                        },
                        new
                        {
                            Id = 7,
                            Address = "Ernakulam, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7872),
                            District = "Ernakulam",
                            DistrictId = 0,
                            Email = "clothsy.ernakulam@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Ernakulam",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00006",
                            WorkingDays = ""
                        },
                        new
                        {
                            Id = 8,
                            Address = "Thrissur, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7874),
                            District = "Thrissur",
                            DistrictId = 0,
                            Email = "clothsy.thrissur@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Thrissur",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00007",
                            WorkingDays = ""
                        },
                        new
                        {
                            Id = 9,
                            Address = "Palakkad, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7875),
                            District = "Palakkad",
                            DistrictId = 0,
                            Email = "clothsy.palakkad@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Palakkad",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00008",
                            WorkingDays = ""
                        },
                        new
                        {
                            Id = 10,
                            Address = "Malappuram, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7876),
                            District = "Malappuram",
                            DistrictId = 0,
                            Email = "clothsy.malappuram@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Malappuram",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00009",
                            WorkingDays = ""
                        },
                        new
                        {
                            Id = 11,
                            Address = "Kozhikode, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7879),
                            District = "Kozhikode",
                            DistrictId = 0,
                            Email = "clothsy.kozhikode@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kozhikode",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00010",
                            WorkingDays = ""
                        },
                        new
                        {
                            Id = 12,
                            Address = "Wayanad, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7880),
                            District = "Wayanad",
                            DistrictId = 0,
                            Email = "clothsy.wayanad@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Wayanad",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00011",
                            WorkingDays = ""
                        },
                        new
                        {
                            Id = 13,
                            Address = "Kannur, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7881),
                            District = "Kannur",
                            DistrictId = 0,
                            Email = "clothsy.kannur@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kannur",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00012",
                            WorkingDays = ""
                        },
                        new
                        {
                            Id = 14,
                            Address = "Kasaragod, Kerala",
                            CloseTime = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 23, 4, 37, 10, 633, DateTimeKind.Utc).AddTicks(7882),
                            District = "Kasaragod",
                            DistrictId = 0,
                            Email = "clothsy.kasaragod@clothsy.in",
                            HubCode = "",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kasaragod",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            Phone = "+91 90000 00013",
                            WorkingDays = ""
                        });
                });

            modelBuilder.Entity("Clothsy.Models.NotificationRead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationReads");
                });

            modelBuilder.Entity("Clothsy.Models.Profile.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HouseAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RoadName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Clothsy.Models.Profile.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("Clothsy.Models.Profile.SupportTicketReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("SupportTicketReplies");
                });

            modelBuilder.Entity("Clothsy.Models.SignupModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Clothsy.Models.Web.Auth.WebUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HubCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebUsers");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.Donation", b =>
                {
                    b.HasOne("Clothsy.Models.Donation.Hub", "AssignedHub")
                        .WithMany()
                        .HasForeignKey("AssignedHubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clothsy.Models.SignupModels.User", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedHub");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.DonationImage", b =>
                {
                    b.HasOne("Clothsy.Models.Donation.Donation", "Donation")
                        .WithMany("Images")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.DonationRequest", b =>
                {
                    b.HasOne("Clothsy.Models.Profile.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clothsy.Models.Donation.Donation", "Donation")
                        .WithMany()
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clothsy.Models.Donation.Donation", null)
                        .WithMany("DonationRequests")
                        .HasForeignKey("DonationId1");

                    b.HasOne("Clothsy.Models.SignupModels.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Donation");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Clothsy.Models.NotificationRead", b =>
                {
                    b.HasOne("Clothsy.Models.SignupModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clothsy.Models.Profile.Address", b =>
                {
                    b.HasOne("Clothsy.Models.SignupModels.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clothsy.Models.Profile.SupportTicket", b =>
                {
                    b.HasOne("Clothsy.Models.SignupModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clothsy.Models.Profile.SupportTicketReply", b =>
                {
                    b.HasOne("Clothsy.Models.Profile.SupportTicket", "Ticket")
                        .WithMany("Replies")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.Donation", b =>
                {
                    b.Navigation("DonationRequests");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Clothsy.Models.Profile.SupportTicket", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Clothsy.Models.SignupModels.User", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
