// <auto-generated />
using System;
using Clothsy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clothsy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260109200902_Notification1")]
    partial class Notification1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clothsy.Models.Donation.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedHubId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClothingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DonationId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DonorUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ThumbnailImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedHubId");

                    b.HasIndex("DonorUserId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.DonationImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DonationId");

                    b.ToTable("DonationImages");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.DonationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("DonationId");

                    b.HasIndex("RequesterId");

                    b.ToTable("DonationRequests");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.Hub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Hubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = " Trivandrum, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7372),
                            District = "Trivandrum",
                            Email = "clothsy.trivandrum@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Trivandrum",
                            Phone = "+91 90000 00000"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kollam, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7376),
                            District = "Kollam",
                            Email = "clothsy.kollam@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kollam",
                            Phone = "+91 90000 00001"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Pathanamthitta, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7378),
                            District = "Pathanamthitta",
                            Email = "clothsy.pathanamthitta@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Pathanamthitta",
                            Phone = "+91 90000 00002"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Alappuzha, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7380),
                            District = "Alappuzha",
                            Email = "clothsy.alappuzha@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Alappuzha",
                            Phone = "+91 90000 00003"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Kottayam, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7382),
                            District = "Kottayam",
                            Email = "clothsy.kottayam@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kottayam",
                            Phone = "+91 90000 00004"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Idukki, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7383),
                            District = "Idukki",
                            Email = "clothsy.idukki@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Idukki",
                            Phone = "+91 90000 00005"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Ernakulam, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7385),
                            District = "Ernakulam",
                            Email = "clothsy.ernakulam@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Ernakulam",
                            Phone = "+91 90000 00006"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Thrissur, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7386),
                            District = "Thrissur",
                            Email = "clothsy.thrissur@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Thrissur",
                            Phone = "+91 90000 00007"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Palakkad, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7388),
                            District = "Palakkad",
                            Email = "clothsy.palakkad@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Palakkad",
                            Phone = "+91 90000 00008"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Malappuram, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7389),
                            District = "Malappuram",
                            Email = "clothsy.malappuram@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Malappuram",
                            Phone = "+91 90000 00009"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Kozhikode, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7391),
                            District = "Kozhikode",
                            Email = "clothsy.kozhikode@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kozhikode",
                            Phone = "+91 90000 00010"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Wayanad, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7392),
                            District = "Wayanad",
                            Email = "clothsy.wayanad@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Wayanad",
                            Phone = "+91 90000 00011"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Kannur, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7393),
                            District = "Kannur",
                            Email = "clothsy.kannur@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kannur",
                            Phone = "+91 90000 00012"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Kasaragod, Kerala",
                            CreatedAt = new DateTime(2026, 1, 9, 20, 9, 1, 937, DateTimeKind.Utc).AddTicks(7395),
                            District = "Kasaragod",
                            Email = "clothsy.kasaragod@clothsy.in",
                            IsActive = true,
                            Name = "Clothsy Central Hub - Kasaragod",
                            Phone = "+91 90000 00013"
                        });
                });

            modelBuilder.Entity("Clothsy.Models.Donation.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedHub")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("DonationId")
                        .IsUnique();

                    b.HasIndex("RequesterId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Clothsy.Models.NotificationRead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationReads");
                });

            modelBuilder.Entity("Clothsy.Models.Profile.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HouseAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RoadName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Clothsy.Models.Profile.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("Clothsy.Models.SignupModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.Donation", b =>
                {
                    b.HasOne("Clothsy.Models.Donation.Hub", "AssignedHub")
                        .WithMany()
                        .HasForeignKey("AssignedHubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clothsy.Models.SignupModels.User", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedHub");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.DonationImage", b =>
                {
                    b.HasOne("Clothsy.Models.Donation.Donation", "Donation")
                        .WithMany("Images")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.DonationRequest", b =>
                {
                    b.HasOne("Clothsy.Models.Profile.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clothsy.Models.Donation.Donation", "Donation")
                        .WithMany()
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clothsy.Models.SignupModels.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Donation");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.Request", b =>
                {
                    b.HasOne("Clothsy.Models.Profile.Address", "DeliveryAddress")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothsy.Models.Donation.Donation", "Donation")
                        .WithOne("Request")
                        .HasForeignKey("Clothsy.Models.Donation.Request", "DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothsy.Models.SignupModels.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Donation");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Clothsy.Models.NotificationRead", b =>
                {
                    b.HasOne("Clothsy.Models.SignupModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clothsy.Models.Profile.Address", b =>
                {
                    b.HasOne("Clothsy.Models.SignupModels.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clothsy.Models.Profile.SupportTicket", b =>
                {
                    b.HasOne("Clothsy.Models.SignupModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clothsy.Models.Donation.Donation", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Clothsy.Models.SignupModels.User", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
